name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
jobs:
  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch repository history for access to tags in tests
        run: git fetch --prune --unshallow --tags
      - name: Install fish shell
        run: brew install fish
      - name: Install fisher and fishtape
        run: curl -sL git.io/fisher | source && fisher install jorgebucaran/{fisher,fishtape}
        shell: fish {0}
      - name: Install tap-diff
        run: $GITHUB_WORKSPACE && npm install tap-diff
        shell: fish {0}
      - name: Test plugin installation
        run: $GITHUB_WORKSPACE && fisher install .
        shell: fish {0}
      - name: Run tests
        run: |
          set -xg FORCE_COLOR 2
          cd $GITHUB_WORKSPACE/test
          fishtape *.fish | $GITHUB_WORKSPACE/node_modules/.bin/tap-diff
        shell: fish {0}
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch repository history for access to tags in tests
        run: git fetch --prune --unshallow --tags
      - name: Install fish shell
        run: |
          sudo apt-add-repository -yn ppa:fish-shell/release-3
          sudo apt-get update
          sudo apt-get install -y fish
      - name: Install fisher and fishtape
        run: curl -sL git.io/fisher | source && fisher install jorgebucaran/{fisher,fishtape}
        shell: fish {0}
      - name: Install tap-diff
        run: $GITHUB_WORKSPACE && npm install tap-diff
        shell: fish {0}
      - name: Test plugin installation
        run: $GITHUB_WORKSPACE && fisher install .
        shell: fish {0}
      - name: Run tests
        run: |
          set -xg FORCE_COLOR 2
          cd $GITHUB_WORKSPACE/test
          fishtape *.fish | $GITHUB_WORKSPACE/node_modules/.bin/tap-diff
        shell: fish {0}
