name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:
jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install fish shell
        uses: fish-shop/install-fish-shell@986c36345f9d9da820797e5368f0dfad4a4a0e29 # v1.0.3
      - name: Syntax check fish files
        uses: fish-shop/syntax-check@v1
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Fetch repository history for access to tags in tests
        run: git fetch --prune --unshallow --tags --force
      - name: Install fish shell
        uses: fish-shop/install-fish-shell@986c36345f9d9da820797e5368f0dfad4a4a0e29 # v1.0.3
      - name: Install pond
        uses: fish-shop/install-plugin@2d758540a20e90f474c98de7a22d3a0f9ddad1b2 # v2.2.6
        with:
          plugin-manager: fisher
          plugins: (pwd)
      - name: Run Fishtape tests
        uses: fish-shop/run-fishtape-tests@5aa4a761c900c58f945e2597d8ac569b5b2dcbeb # v1.5.3
        with:
          pattern: tests/**.fish
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        plugin-manager: [fisher, oh-my-fish]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install fish shell
        uses: fish-shop/install-fish-shell@986c36345f9d9da820797e5368f0dfad4a4a0e29 # v1.0.3
      - name: Install pond using ${{ matrix.plugin-manager }}
        uses: fish-shop/install-plugin@2d758540a20e90f474c98de7a22d3a0f9ddad1b2 # v2.2.6
        with:
          plugin-manager: ${{ matrix.plugin-manager }}
          plugins: (pwd)
      - name: Check pond is installed
        run: functions -q pond
        shell: fish {0}
