name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:
jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install fish shell
        uses: fish-actions/install-fish@d6d9d26231a15f8d9a6b3e74b3db45512440e3e8 # v1.1.0
      - name: Syntax check fish files
        uses: fish-shop/syntax-check@v1
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Fetch repository history for access to tags in tests
        run: git fetch --prune --unshallow --tags --force
      - name: Install fish shell
        uses: fish-actions/install-fish@d6d9d26231a15f8d9a6b3e74b3db45512440e3e8 # v1.1.0
      - name: Install pond
        uses: fish-shop/install-plugin@2b887aa9b96fd16c1fd895147b51d8424c43a4c1 # v2.2.0
        with:
          plugin-manager: fisher
          plugins: (pwd)
      - name: Run Fishtape tests
        uses: fish-shop/run-fishtape-tests@91af3b94963ffb7209a6a87d41be7267000296ae # v1.5.1
        with:
          pattern: tests/**.fish
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        plugin-manager: [fisher, oh-my-fish]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install fish shell
        uses: fish-actions/install-fish@d6d9d26231a15f8d9a6b3e74b3db45512440e3e8 # v1.1.0
      - name: Install pond using ${{ matrix.plugin-manager }}
        uses: fish-shop/install-plugin@2b887aa9b96fd16c1fd895147b51d8424c43a4c1 # v2.2.0
        with:
          plugin-manager: ${{ matrix.plugin-manager }}
          plugins: (pwd)
      - name: Check pond is installed
        run: functions -q pond
        shell: fish {0}
