name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:
jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install fish shell
        uses: fish-shop/install-fish-shell@b72efc26566d96fdd54c8891807eee2ee4591ccd # v1.0.13
      - name: Syntax check fish files
        uses: fish-shop/syntax-check@72c20491d71a1104c07c266572041480228e196b # v2.1.1
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Fetch repository history for access to tags in tests
        run: git fetch --prune --unshallow --tags --force
      - name: Install fish shell
        uses: fish-shop/install-fish-shell@b72efc26566d96fdd54c8891807eee2ee4591ccd # v1.0.13
      - name: Install pond
        uses: fish-shop/install-plugin@7ea6608db3b5df8deb3548d04fd89f73b37efc63 # v2.3.3
        with:
          plugin-manager: fisher
          plugins: ${{ github.workspace }}
      - name: Run Fishtape tests
        uses: fish-shop/run-fishtape-tests@6fa77f08085359ba4100103986a0347af6347fa0 # v2.3.1
        with:
          patterns: tests/**.fish
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        plugin-manager: [fisher, oh-my-fish]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install fish shell
        uses: fish-shop/install-fish-shell@b72efc26566d96fdd54c8891807eee2ee4591ccd # v1.0.13
      - name: Install pond using ${{ matrix.plugin-manager }}
        uses: fish-shop/install-plugin@7ea6608db3b5df8deb3548d04fd89f73b37efc63 # v2.3.3
        with:
          plugin-manager: ${{ matrix.plugin-manager }}
          plugins: ${{ github.workspace }}
      - name: Check pond is installed
        run: functions -q pond
        shell: fish {0}
