name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:
jobs:
  indentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install fish shell
        uses: fish-shop/install-fish-shell@71e42122c25804f971f89857d700c68a7efb3855 # v1.0.11
      - name: Check indentation
        uses: fish-shop/indent-check@action-implementation
        with:
          patterns: '{conf.d,completions,hooks,functions,tests}/**.fish'
  syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install fish shell
        uses: fish-shop/install-fish-shell@a138cde6621a975172321d698e3bb025ff2f2004 # v1.0.15
      - name: Syntax check fish files
        uses: fish-shop/syntax-check@4ff208e24be16ff0d9538270f27846e951e1f0a4 # v2.2.1
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Fetch repository history for access to tags in tests
        run: git fetch --prune --unshallow --tags --force
      - name: Install fish shell
        uses: fish-shop/install-fish-shell@a138cde6621a975172321d698e3bb025ff2f2004 # v1.0.15
      - name: Install pond
        uses: fish-shop/install-plugin@10287f06ef7243f565de7d6f9bb3e4f5afe7143d # v2.3.4
        with:
          plugin-manager: fisher
          plugins: ${{ github.workspace }}
      - name: Run Fishtape tests
        uses: fish-shop/run-fishtape-tests@5ecc10a0afcdf7ed4d2f51becfe3ed7e7f180abd # v2.3.2
        with:
          patterns: tests/**.fish
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        plugin-manager: [fisher, oh-my-fish]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install fish shell
        uses: fish-shop/install-fish-shell@a138cde6621a975172321d698e3bb025ff2f2004 # v1.0.15
      - name: Install pond using ${{ matrix.plugin-manager }}
        uses: fish-shop/install-plugin@10287f06ef7243f565de7d6f9bb3e4f5afe7143d # v2.3.4
        with:
          plugin-manager: ${{ matrix.plugin-manager }}
          plugins: ${{ github.workspace }}
      - name: Check pond is installed
        run: functions -q pond
        shell: fish {0}
