name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install fish shell
        uses: fish-actions/install-fish@v1
      - name: Syntax check fish files
        uses: fish-shop/syntax-check@v1
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Fetch repository history for access to tags in tests
        run: git fetch --prune --unshallow --tags
      - name: Install fish shell
        uses: fish-actions/install-fish@v1
      - name: Install fisher and fishtape
        uses: fish-shop/install-plugin@v1
        with:
          plugin-manager: fisher
          plugins: jorgebucaran/{fisher,fishtape}
      - name: Install pond
        run: fisher install .
        shell: fish {0}
      - name: Run Fishtape tests
        uses: fish-shop/run-fishtape-tests@main
        with:
          pattern: tests/**.fish
  fisher-install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install fish shell
        uses: fish-actions/install-fish@v1
      - name: Install fisher
        uses: fish-shop/install-plugin-manager@v1
        with:
          plugin-manager: fisher
      - name: Test plugin installation
        run: fisher install .
        shell: fish {0}
      - name: Check pond is installed
        run: functions -q pond
        shell: fish {0}
  oh-my-fish-install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install fish shell
        uses: fish-actions/install-fish@v1
      - name: Install oh-my-fish
        uses: fish-shop/install-plugin-manager@v1
        with:
          plugin-manager: oh-my-fish
      - name: Test plugin installation
        run: omf install (pwd)
        shell: fish {0}
      - name: Check pond is installed
        run: functions -q pond
        shell: fish {0}
  plug-fish-install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install fish shell
        uses: fish-actions/install-fish@v1
      - name: Install plug.fish
        uses: fish-shop/install-plugin-manager@v1
        with:
          plugin-manager: plug.fish
      - name: Test plugin installation
        run: plug install .
        shell: fish {0}
      - name: Check pond is installed
        run: functions -q pond
        shell: fish {0}
